### ISSUE TITLE
smol-rs?

### ISSUE THREAD

**Issue by zeenix** [zseri/as-any#1]
Hi @zseri,

I see that you've moved this crate under smol-rs. This seems like a very useful crate but I don't see the relevance to smol-rs project. Was this discussed somewhere between @smol-rs/admins?

**Comment by zseri** [comment]
I haven't really discussed it and I don't expect the crate to pretty much change at all (it's really simple after all) unless some really low-level change in the rust standard library makes it necessary, the main reason to move it here are therefore bus factor reasons (because the old org where it was developed as originally part of multiple event application-local pub/sub queues stopped working at all). This might've been the wrong choice. I basically wanted to desolve the basically defunct previous org and needed to move the crate somewhere, and this was the only crate that was both simple and really low-level. I could move it again after all to reside under my standard github namespace in case smol-rs as an org would be too inappropriate.

**Comment by zeenix** [comment]
@zseri Thanks for explaining. Yeah, **IMO** it doesn't belong here and would give the wrong impression to people that it's part of smol-rs project so I'd prefer if you moved it in your personal space. Having said that, I'm not the dictator here (nor I want to be) so it'd be good to hear from another maintainer as well.
